
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AGUA APAGAR ENCENDER INICIAR NUMERO SET TEMPERATURAcomando : ENCENDER\n| APAGAR\n| INICIARcomando : SET AGUA NUMERO\n| SET TEMPERATURA NUMERO'
    
_lr_action_items = {'ENCENDER':([0,],[2,]),'APAGAR':([0,],[3,]),'INICIAR':([0,],[4,]),'SET':([0,],[5,]),'$end':([1,2,3,4,8,9,],[0,-1,-2,-3,-4,-5,]),'AGUA':([5,],[6,]),'TEMPERATURA':([5,],[7,]),'NUMERO':([6,7,],[8,9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'comando':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> comando","S'",1,None,None,None),
  ('comando -> ENCENDER','comando',1,'p_comando_simple','lavadora.py',97),
  ('comando -> APAGAR','comando',1,'p_comando_simple','lavadora.py',98),
  ('comando -> INICIAR','comando',1,'p_comando_simple','lavadora.py',99),
  ('comando -> SET AGUA NUMERO','comando',3,'p_comando_param','lavadora.py',108),
  ('comando -> SET TEMPERATURA NUMERO','comando',3,'p_comando_param','lavadora.py',109),
]
